### ISSUE TITLE
URL generation error from localhost controller

### ISSUE THREAD

**Issue by EminenceHC** [pdfkit/pdfkit#310] opened 2015-06-05 20:10 UTC
PDF generation works from console, but not from inside my rails controller when trying to create PDF:

kit = PDFKit.new('http://localhost:3000/intake_agreements/1')
kit.to_file('public/PDF/kit.pdf')

http://localhost:3000/intake_agreements/1 is SUPER barebones, no relative stylesheets/javascript with the most bare bones custom layout.

If I change command to PDFKit.new('http://www.google.com') it will save to a PDF just fine. It seems to just have trouble from localhost URL. I have tried solutions from just about every post on PDFkit.

wkhtmltopdf 0.12.2.1
Ruby 2.0.0p594
Rails 4.0.2

Always hangs on:
Loading pages (1/6)
[======> ] 10%

When I stop the server I receive error:

command failed (exitstatus=1): /Users/travis.glover/.rvm/gems/ruby-2.0.0-p594/gems/wkhtmltopdf-binary-edge-0.12.2.1/bin/wkhtmltopdf --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 http://localhost:3000/intake_agreements/1 public/PDF/kit.pdf

**Comment by sigmavirus24** [comment] 2015-06-09 03:20
What happens if you start the server and run

```
/Users/travis.glover/.rvm/gems/ruby-2.0.0-p594/gems/wkhtmltopdf-binary-edge-0.12.2.1/bin/wkhtmltopdf --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 http://localhost:3000/intake_agreements/1 public/PDF/kit.pdf
```

From a command-line?

**Comment by EminenceHC** [comment] 2015-06-09 22:12
That works, but because the command is issued outside of the rails application, it creates a PDF of my devise login screen.

**Comment by cdwort** [comment] 2015-06-12 02:54
To get around login issues, could you instead have a one-off route (http://localhost:3000/test) that just runs that command and logs the output?

```
command = "/Users/travis.glover/.rvm/gems/ruby...."
output = %x[command]
Rails.logger.debug output
```

What we are trying to determine is whether this is a PDFKit issue or a wkHTMLtoPDF issue. PDFKit is really a thin wrapper around wkHTMLtoPDF and the exit status suggests that we need more information out of wkHTMLtoPDF about what is wrong.

**Comment by EminenceHC** [comment] 2015-06-12 15:33
I was not able to log any output from the code provided above. I sent a get request to a controller method with that code in it. I also tried to use Raise.output.inspect instead of Rails.logger.debug output

It might help to note that wkhtmltopdf library works with Wicked PDF from inside my application with the same wkhtmltopdf gem I am using for PDFkit.

**Comment by sigmavirus24** [comment] 2015-08-22 14:48
> It might help to note that wkhtmltopdf library works with Wicked PDF from inside my application with the same wkhtmltopdf gem I am using for PDFkit.

I have no clue what this means. :(

**Comment by cdwort** [comment] 2015-08-22 15:43
@sigmavirus24 I think the point that @EminenceHC is trying to make is that if it's working on WickedPDF, the suspect is not wkhtmltopdf.

I think what's confusing might be the reference to `wkhtmltopdf gem`, but I think that's just confusion about the fact that wkhtmltopdf is actually a command-line utility.

**Comment by cdwort** [comment] 2015-08-22 19:38
From the log entry, it is clear that this is a wkhtmltopdf issue. The difference between WickedPDF and PDFKit would be in the way they might alter the markup, but that's not happening here. There is some issue with the markup, but we don't have any way to recreate that without access to the application.

Unlike many other projects, PDFKit doesn't have a requirement to create a repo that reproduces the problem, but I don't see anyway for us to track this down without that.

I am closing due to our inability to recreate. We can reopen if/when we get a repo that can reproduce.

**Closed by cdwort** 2015-08-22 19:38 UTC
Labels: propose close

**Comment by fera2k** [comment] 2024-05-07 14:31
I had the same issue as described in the OP. But it was due to the server running with only 1 thread. If I allowed the app to run with 2 threads, it worked as expected.
`RAILS_MAX_THREADS=2 bundle exec rails s -p 3000`
