### ISSUE TITLE
PDFKIT works on local but returning empty pdf on heroku

### ISSUE THREAD

**Issue by harryj** [pdfkit/pdfkit#342] opened 2015-12-16 01:17 UTC
I have wkhtmltopdf binaries in my bin folder and my initializer is as follows:
```
PDFKit.configure do |config|
  # if ["development"].include?(Rails.env)
  if ENV["TRIPCIPE_ENV"] == "local"
   config.wkhtmltopdf = Rails.root.join('bin', 'wkhtmltopdf').to_s
  else
   config.wkhtmltopdf = Rails.root.join('bin', 'wkhtmltopdf-amd64').to_s
  end  
 end
```

my controller code looks like this
```
html = render_to_string(:action => "pdf", :layout => false)
kit = PDFKit.new(html)
send_data(kit.to_pdf, :filename => 'report.pdf', :type => 'application/pdf', :disposition => 'inline')
```

And it works fine locally but when I deploy on heroku I just get an empty 1 page pdf file.

Any ideas or help would be appreciated, thanks.

**Comment by cdwort** [comment] 2015-12-16 07:00
Hey @harryj 

Thanks for reaching out. 

It looks like your issue is just how to configure the location of wkhtmltopdf on Heroku, not reporting a bug in the PDFKit gem. In the future, I would recommend posting on StackOverflow unless you have a bug report.

Some ideas:

You're pointing PDFKit at a binary supposedly at `Rails.root.join('bin', 'wkhtmltopdf-amd64')`. How did you get wkhtmltopdf installed on Heroku? Did you confirm with `heroku run "which wkhtmltopdf" -a your-app-name-on-heroku` that this is the correct location?

It looks like you are manually configuring your settings. Is there a reason you'd rather not use a gem to do all this for you? For instance https://github.com/rposborne/wkhtmltopdf-heroku?

We also have a documentation page here that has options for manually setting up wkhtmltopdf on Heroku: https://github.com/pdfkit/pdfkit/wiki/Use-with-Heroku. That documentation is probably out of date. Is this what you followed?

Thanks, 
Amy

**Comment by sigmavirus24** [comment] 2015-12-16 16:24
Since this is not a bug in pdfkit, I'm closing this.

**Closed by sigmavirus24** 2015-12-16 16:24 UTC
