### ISSUE TITLE
PDFkit is not considering Image orientation details

### ISSUE THREAD

**Issue by mounikakella** [pdfkit/pdfkit#454] opened 2019-10-11 07:30 UTC
The PDF generating is not considering the Image orientation details and printing the image in wrong ways.. How can I fix this?

**Comment by serene** [comment] 2019-10-11 13:53
Have you verified that this is an issue with pdfkit and not with the wkhtmltopdf library?

Please note that pdfkit is just a wrapper around the wkhtmltopdf library to allow it to be used in ruby. 

I'm going to close this issue, but if you are able to reproduce the problem using pdfkit, but cannot reproduce it by directly executing wkhtmltopdf from the command line, then feel free to re-open it.

**Closed by serene** 2019-10-11 13:53 UTC

**Comment by mounikakella** [comment] 2019-10-14 05:24
It worked well when I am giving an image path rather than the buffer.
I got this problem when Im trying to use buffer.

On Fri, Oct 11, 2019 at 7:23 PM Serene Yew <notifications@github.com> wrote:
>
> Closed #454.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Thanks,
Mounika Kella.
